export const clientData = [
  {
    id: 1,
    name: 'Samir',
    phoneNumber: '1234567890',
    role: 'Provider',
    address: 'asdasda',
    city: 'Berlin',
    orderCount: 10,
  },
  {
    id: 2,
    name: 'Juan',
    phoneNumber: '1234567890',
    role: 'user',
    address: 'asdasda',
    city: 'Monaco',
    orderCount: 5,
  },
  {
    id: 3,
    name: 'Alejandro',
    phoneNumber: '3004218478',
    role: 'user',
    address: 'asdasda',
    city: 'Malambo',
    orderCount: 1,
  },
  {
    id: 4,
    name: 'Jesus',
    phoneNumber: '00000000',
    role: 'user',
    address: 'asdasda',
    city: 'singapur',
    orderCount: 20,
  },
  {
    id: 4,
    name: 'Jesus',
    phoneNumber: '00000000',
    role: 'user',
    address: 'asdasda',
    city: 'singapur',
    orderCount: 20,
  },
  {
    id: 4,
    name: 'Jesus',
    phoneNumber: '00000000',
    role: 'user',
    address: 'asdasda',
    city: 'singapur',
    orderCount: 20,
  },
  {
    id: 4,
    name: 'Jesus',
    phoneNumber: '00000000',
    role: 'user',
    address: 'asdasda',
    city: 'singapur',
    orderCount: 20,
  },
  {
    id: 4,
    name: 'Jesus',
    phoneNumber: '00000000',
    role: 'user',
    address: 'asdasda',
    city: 'singapur',
    orderCount: 20,
  },
  {
    id: 4,
    name: 'Jesus',
    phoneNumber: '00000000',
    role: 'user',
    address: 'asdasda',
    city: 'singapur',
    orderCount: 20,
  },
  {
    id: 4,
    name: 'Jesus',
    phoneNumber: '00000000',
    role: 'user',
    address: 'asdasda',
    city: 'singapur',
    orderCount: 20,
  },
]